/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppRecurringRouteImport } from './routes/_app/recurring'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events/$eventId'
import { Route as AppSplitIndexRouteImport } from './routes/_app/split/index'
import { Route as AppSplitGroupsGroupIdRouteImport } from './routes/_app/split/groups/$groupId'
import { Route as AppSplitPeoplePersonIdRouteImport } from './routes/_app/split/people/$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppSplitIndexRoute = AppSplitIndexRouteImport.update({
  id: '/split/',
  path: '/split/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplitGroupsGroupIdRoute = AppSplitGroupsGroupIdRouteImport.update({
  id: '/split/groups/$groupId',
  path: '/split/groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppSplitPeoplePersonIdRoute = AppSplitPeoplePersonIdRouteImport.update({
  id: '/split/people/$personId',
  path: '/split/people/$personId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/more': typeof AppMoreRoute
  '/recurring': typeof AppRecurringRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/split/': typeof AppSplitIndexRoute
  '/split/groups/$groupId': typeof AppSplitGroupsGroupIdRoute
  '/split/people/$personId': typeof AppSplitPeoplePersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/more': typeof AppMoreRoute
  '/recurring': typeof AppRecurringRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/split': typeof AppSplitIndexRoute
  '/split/groups/$groupId': typeof AppSplitGroupsGroupIdRoute
  '/split/people/$personId': typeof AppSplitPeoplePersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/split/': typeof AppSplitIndexRoute
  '/_app/split/groups/$groupId': typeof AppSplitGroupsGroupIdRoute
  '/_app/split/people/$personId': typeof AppSplitPeoplePersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/goals'
    | '/more'
    | '/recurring'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/accounts/$accountId'
    | '/events/$eventId'
    | '/accounts/'
    | '/events/'
    | '/split/'
    | '/split/groups/$groupId'
    | '/split/people/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/goals'
    | '/more'
    | '/recurring'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/accounts/$accountId'
    | '/events/$eventId'
    | '/accounts'
    | '/events'
    | '/split'
    | '/split/groups/$groupId'
    | '/split/people/$personId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/_app/budgets'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/more'
    | '/_app/recurring'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/accounts/$accountId'
    | '/_app/events/$eventId'
    | '/_app/accounts/'
    | '/_app/events/'
    | '/_app/split/'
    | '/_app/split/groups/$groupId'
    | '/_app/split/people/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/split/': {
      id: '/_app/split/'
      path: '/split'
      fullPath: '/split/'
      preLoaderRoute: typeof AppSplitIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/split/groups/$groupId': {
      id: '/_app/split/groups/$groupId'
      path: '/split/groups/$groupId'
      fullPath: '/split/groups/$groupId'
      preLoaderRoute: typeof AppSplitGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/split/people/$personId': {
      id: '/_app/split/people/$personId'
      path: '/split/people/$personId'
      fullPath: '/split/people/$personId'
      preLoaderRoute: typeof AppSplitPeoplePersonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppMoreRoute: typeof AppMoreRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppSplitIndexRoute: typeof AppSplitIndexRoute
  AppSplitGroupsGroupIdRoute: typeof AppSplitGroupsGroupIdRoute
  AppSplitPeoplePersonIdRoute: typeof AppSplitPeoplePersonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetsRoute: AppBudgetsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppMoreRoute: AppMoreRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppSplitIndexRoute: AppSplitIndexRoute,
  AppSplitGroupsGroupIdRoute: AppSplitGroupsGroupIdRoute,
  AppSplitPeoplePersonIdRoute: AppSplitPeoplePersonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
