import {
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Cake,
  Car,
  Circle,
  CircleEllipsis,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Flame,
  Fuel,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  type LucideIcon,
  Music,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  PlusCircle,
  Receipt,
  RotateCcw,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Target,
  Tent,
  TrendingUp,
  Tv,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import { cn } from "@/lib/utils";

export const ICONS: Record<string, LucideIcon> = {
  users: Users,
  "credit-card": CreditCard,
  "party-popper": PartyPopper,
  cake: Cake,
  music: Music,
  tent: Tent,
  flame: Flame,
  heart: Heart,
  briefcase: Briefcase,
  laptop: Laptop,
  store: Store,
  percent: Percent,
  "trending-up": TrendingUp,
  gift: Gift,
  "rotate-ccw": RotateCcw,
  "plus-circle": PlusCircle,
  home: Home,
  "shopping-basket": ShoppingBasket,
  utensils: Utensils,
  "heart-pulse": HeartPulse,
  plane: Plane,
  "shopping-bag": ShoppingBag,
  receipt: Receipt,
  fuel: Fuel,
  "graduation-cap": GraduationCap,
  clapperboard: Clapperboard,
  landmark: Landmark,
  shield: Shield,
  sparkles: Sparkles,
  "circle-ellipsis": CircleEllipsis,
  "shopping-cart": ShoppingCart,
  coffee: Coffee,
  car: Car,
  bus: Bus,
  bike: Bike,
  smartphone: Smartphone,
  wifi: Wifi,
  zap: Zap,
  tv: Tv,
  shirt: Shirt,
  pill: Pill,
  dumbbell: Dumbbell,
  baby: Baby,
  "paw-print": PawPrint,
  "book-open": BookOpen,
  wrench: Wrench,
  wallet: Wallet,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  target: Target,
  circle: Circle,
};

export const ICON_NAMES = Object.keys(ICONS);

export const COLORS = [
  "#16a34a",
  "#0d9488",
  "#0891b2",
  "#0ea5e9",
  "#2563eb",
  "#4f46e5",
  "#7c3aed",
  "#a855f7",
  "#d946ef",
  "#db2777",
  "#e11d48",
  "#dc2626",
  "#ea580c",
  "#f97316",
  "#eab308",
  "#78716c",
  "#64748b",
  "#0f766e",
];

export function CategoryIcon({
  icon,
  color,
  className,
  size = "md",
}: {
  icon: string;
  color: string;
  className?: string;
  size?: "sm" | "md" | "lg";
}) {
  const Icon = ICONS[icon] ?? Circle;
  return (
    <span
      className={cn(
        "inline-grid shrink-0 place-items-center rounded-full",
        size === "sm" && "size-8 [&_svg]:size-4",
        size === "md" && "size-10 [&_svg]:size-5",
        size === "lg" && "size-12 [&_svg]:size-6",
        className,
      )}
      style={{ backgroundColor: `${color}1f`, color }}
    >
      <Icon />
    </span>
  );
}
